theme: jekyll-theme-leap-day
title: Data Science Portfolio
description: Alessandro Guarnieri, M.Sc. Applied Physics | aleguarnieri91@gmail.com 
plugins:
  - jemoji
footer:
  links:
    - url: "https://www.linkedin.com/in/alessandro-g-5143679a/"
