theme: jekyll-theme-slate
title: Alessandro's Data Science Portfolio
description: Feel free to explore and comment on my exercises and projects I built up here for my self-learning and education on the data science topic
