theme: jekyll-theme-leap-day
title: Data Science Portfolio
description: Alessandro Guarnieri, M.Sc. Applied Physics | aleguarnieri91@gmail.com 
plugins:
  - jemoji
  
linkedin_username: alessandro-g-5143679a/
